server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DreitonWashington/ead-config-server-repo
          default-label: main
          username: DreitonWashington
          password: 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

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
