server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DreitonWashington/ead-config-server-repo
          default-label: main
          username: DreitonWashington
          password: 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

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
